export default {
  USER_FETCH_USERDATA: 'USER_FETCH_USERDATA',
  USER_FETCH_USERDATA_REJECTED: 'USER_FETCH_USERDATA_REJECTED',
  USER_FETCH_USERDATA_FULFILLED: 'USER_FETCH_USERDATA_FULFILLED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_REJECTED: 'USER_LOGIN_REJECTED',
  USER_LOGIN_FULFILLED: 'USER_LOGIN_FULFILLED',
  USER_AUTOLOGIN: 'USER_AUTOLOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGOUT_FULFILLED: 'USER_LOGOUT_FULFILLED',
};
