import { ITypes } from './contracts/ITypes';

const types: ITypes = {
  SEARCH_ISNEWQUERY: 'SEARCH_ISNEWQUERY',
  SEARCH_SETCURRENTQUERY: 'SEARCH_SETCURRENTQUERY',
  SEARCH_SETCURRENTQUERY_FULFILLED: 'SEARCH_SETCURRENTQUERY_FULFILLED',
  SEARCH_FETCH: 'SEARCH_FETCH',
  SEARCH_FETCH_FULFILLED: 'SEARCH_FETCH_FULFILLED',
};

export default types;
